version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zero_obstacle_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zero_obstacle_worker
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A workers.celery_worker.celery_app worker --loglevel=info

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zero_obstacle_scheduler
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A workers.scheduler.celery_app beat --loglevel=info

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
