version: "3.9"

services:
  api:
    build: ./api
    container_name: zoc_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7
    container_name: zoc_redis
    ports:
      - "6379:6379"

  celery_worker:
    build: ./api
    container_name: zoc_worker
    env_file:
      - .env
    depends_on:
      - redis
    command: ["celery", "-A", "workers.celery_worker.celery", "worker", "--loglevel=info"]
